#!/bin/bash
GREEN='\033[0;32m'
BLUE='\033[0;34m'
BIGBLUE='\033[1;34m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m'


INSTALL_DIR="/home/$USER/.local/bin"
SCRIPT="aws-quick-switch"
SOURCE="/home/$USER/.zshrc"

if [ -f "$INSTALL_DIR/$SCRIPT" ]; then
    cp "$SCRIPT" "$INSTALL_DIR"/"$SCRIPT"
    chmod +x "$INSTALL_DIR"/"$SCRIPT"
    printf "${GREEN}AWS Quick Switch Updated successfully...${NC}\n"
    exit 0
else
    if [ -f "$INSTALL_DIR/aws_quick_switch.sh" ]; then
        rm "$INSTALL_DIR/aws_quick_switch.sh"
        sed '/alias aws-sp/d' $SOURCE > zshrc.backup
        cat zshrc.backup > $SOURCE
        printf "${GREEN}AWS Quick Switch Previous version ${RED}Removed${GREEN} successfully...${NC}\n"
    fi
    
    cp "$SCRIPT" "$INSTALL_DIR"/"$SCRIPT"
    chmod +x "$INSTALL_DIR"/"$SCRIPT"
    
    printf "${GREEN}AWS Quick Switch Installed successfully...${NC}\n"
    
    echo "alias aws-sp='function a(){if [ ! -z \$1 ];then \$(aws-quick-switch \$1); else; aws-quick-switch; fi;  };a'" >> ${SOURCE}
    printf "${GREEN}Added ALIAS for aws-sp in ${YELLOW}$SOURCE${YELLOW}...${NC}\n"
fi


